query GetOrganisation($organisationID: ID!) {
  getOrganisation(id: $organisationID) {
    ... on Organisation {
      id
      code
      name
      totalNumberOfActiveUsers
      totalNumberOfUsers
      totalNumberOfCompletedScreenings
      totalNumberOfIncompletedScreenings
      totalNumberOfSuggestionsClicked
      totalNumberOfSuggestionsViewed
      logoURL
      logoBase64
      themeColor
      organisationType {
        ... on OrganisationType {
          id
          description
          name
          identifier
        }
      }
      _deleted
      _lastChangedAt
      _version
    }
  }
}
