query ListAllProfileSuggestionsByProfile($profileID: ID) {
  listProfileSuggestions(filter: {profileID: {eq: $profileID}}) {
    items {
      ... on ProfileSuggestion {
        id
        createdAt
        updatedAt
        profileID
        suggestionID
        owner
        profile {
          ... on Profile {
            id
          }
        }
        suggestion {
          ... on Suggestion {
            id
            createdAt
            updatedAt
            description
            icon
            index
            isHidden
            name
            numberOfClicks
            numberOfViews
            routePath
            url
            uri
            suggestionActivityId
            activity {
              ... on Activity {
                id
                createdAt
                updatedAt
                description
                duration
                name
                activityActivityTypeId
                activityType {
                  ... on ActivityType {
                    id
                    createdAt
                    updatedAt
                    description
                    identifier
                    name
                  }
                }
                reward {
                  ... on Reward {
                    id
                    createdAt
                    updatedAt
                    description
                    name
                    rewardCredits
                    maxNumberOfRedemptions
                    rewardType {
                      ... on RewardType {
                        id
                        createdAt
                        updatedAt
                        description
                        identifier
                        name
                      }
                    }
                  }
                }
              }
            }
            selfCare {
              ... on SelfCare {
                id
                createdAt
                updatedAt
                description
                name
                icon
                index
                numberOfAvailableSlots
                numberOfTotalSlots
                routePath
                selfCareActivityId
                activity {
                  ... on Activity {
                    id
                    createdAt
                    updatedAt
                    description
                    name
                    activityActivityTypeId
                    activityType {
                      ... on ActivityType {
                        id
                        createdAt
                        updatedAt
                        description
                        name
                        identifier
                      }
                    }
                    reward {
                      ... on Reward {
                        id
                        createdAt
                        updatedAt
                        description
                        name
                        rewardCredits
                        maxNumberOfRedemptions
                        rewardType {
                          ... on RewardType {
                            id
                            createdAt
                            updatedAt
                            description
                            identifier
                            name
                          }
                        }
                      }
                    }
                  }
                }
                selfCareSelfCareTypeId
                selfCareType {
                  ... on SelfCareType {
                    id
                    identifier
                    name
                  }
                }
                url
                profiles {
                  items {
                    ... on SelfCareUsage {
                      id
                      profileID
                      selfCareID
                    }
                  }
                }
              }
            }
            _lastChangedAt
            _deleted
            _version
          }
        }
        _deleted
        _lastChangedAt
        _version
      }
    }
  }
}
