query GetUser($userID: ID!) {
  getUser(id: $userID) {
    ... on User {
      id
      externalUserID
      emailAddress
      deletedAt
      telegramId
      telegramChatId
      username
      userType {
        ... on UserType {
          id
          description
          name
          identifier
        }
      }
      photoBase64
      photoURL
      profile {
        ... on Profile {
          id
          createdAt
          updatedAt
          age
          gender
          weight
          weightUnit
          weightUnitName
          height
          heightUnit
          heightUnitName
          bodyMassIndex
          mood
          stressLevel
          stressIndex
          oxygenLevel
          oxygenSaturationLevel
          respiratoryRate
          systolicBloodPressure
          diastolicBloodPressure
          heartRate
          heartRateVariability
          sympatheticNervousSystemIndex
          timezone
          assessments(limit: 999999999) {
            items {
              ... on Assessment {
                id
                createdAt
                updatedAt
                startDate
                endDate
                mood
                stressLevel
                stressIndex
                oxygenLevel
                oxygenSaturationLevel
                respiratoryRate
                systolicBloodPressure
                diastolicBloodPressure
                heartRate
                heartRateManual
                heartRateManualSource
                heartRateVariability
                sympatheticNervousSystemIndex
                score
                profileID
                assessmentSelfCareId
                selfCare {
                  ... on SelfCare {
                    id
                    createdAt
                    updatedAt
                    description
                    name
                    icon
                    index
                    numberOfAvailableSlots
                    numberOfTotalSlots
                    routePath
                    selfCareActivityId
                    activity {
                      ... on Activity {
                        id
                        createdAt
                        updatedAt
                        description
                        duration
                        name
                        activityActivityTypeId
                        activityType {
                          ... on ActivityType {
                            id
                            createdAt
                            updatedAt
                            description
                            identifier
                            name
                          }
                        }
                        reward {
                          ... on Reward {
                            id
                            createdAt
                            updatedAt
                            description
                            name
                            rewardCredits
                            maxNumberOfRedemptions
                            rewardType {
                              ... on RewardType {
                                id
                                createdAt
                                updatedAt
                                description
                                identifier
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                    selfCareSelfCareTypeId
                    selfCareType {
                      ... on SelfCareType {
                        id
                        createdAt
                        updatedAt
                        description
                        identifier
                        name
                      }
                    }
                    url
                  }
                }
                _version
                _deleted
              }
            }
          }
          activities {
            items {
              ... on ProfileActivity {
                id
              }
            }
          }
          notifications {
            items {
              ... on Notification {
                id
              }
            }
          }
          preferences {
            items {
              ... on ProfilePreference {
                id
              }
            }
          }
          selfCareUsages {
            items {
              ... on SelfCareUsage {
                id
              }
            }
          }
          _version
          _deleted
        }
      }
      groups {
        items {
          ... on UserGroup {
            id
            groupID
            group {
              ... on Group {
                id
                createdAt
                updatedAt
                description
                icon
                identifier
                index
                isApproved
                isHidden
                name
                numberOfClicks
                numberOfQuestions
                numberOfUsers
                numberOfViews
                numberOfVotes
                organisationID
                organisation {
                  ... on Organisation {
                    id
                    code
                    name
                  }
                }
                suggesterID
                suggester {
                  ... on User {
                    id
                    username
                  }
                }
                groupGroupTypeId
                groupType {
                  ... on GroupType {
                    id
                    description
                    icon
                    identifier
                    name
                    organisationID
                  }
                }
              }
            }
            userID
            user {
              ... on User {
                id
              }
            }
          }
        }
      }
      organisations {
        items {
          ... on OrganisationUser {
            id
            organisation {
              id
              code
              name
              logoURL
              themeColor
              telegramId
              secretCode
            }
          }
        }
      }
      notifications {
        items {
          ... on Notification {
            id
          }
        }
      }
      _deleted
      _lastChangedAt
      _version
    }
  }
}
