mutation CreateAnswer($input: CreateAnswerInput!) {
  createAnswer(input: $input) {
    ... on Answer {
      id
      createdAt
      updatedAt
      description
      identifier
      index
      isHidden
      name
      numberOfClicks
      numberOfComments
      numberOfVotes
      numberOfViews
      userID
      user {
        ... on User {
          id
          username
          photoBase64
        }
      }
      questionID
      question {
        ... on Question {
          id
          description
          name
        }
      }
      comments {
        items {
          ... on Comment {
            id
            createdAt
            updatedAt
            description
            identifier
            index
            isHidden
            name
            numberOfClicks
            numberOfVotes
            numberOfViews
            userID
            answerID
            files {
              items {
                ... on CommentFile {
                  id
                  createdAt
                  updatedAt
                  isHidden
                  key
                  name
                  url
                  userID
                  commentID
                  _deleted
                  _lastChangedAt
                  _version
                }
              }
            }
            votes {
              items {
                ... on CommentVote {
                  id
                  createdAt
                  updatedAt
                  isHidden
                  userID
                  commentID
                  _deleted
                  _lastChangedAt
                  _version
                }
              }
            }
            _deleted
            _lastChangedAt
            _version
          }
        }
      }
      files {
        items {
          ... on AnswerFile {
            id
            createdAt
            updatedAt
            isHidden
            key
            name
            url
            userID
            answerID
            _deleted
            _lastChangedAt
            _version
          }
        }
      }
      votes {
        items {
          ... on AnswerVote {
            id
            createdAt
            updatedAt
            isHidden
            userID
            answerID
            _deleted
            _lastChangedAt
            _version
          }
        }
      }
      _deleted
      _lastChangedAt
      _version
    }
  }
}
