mutation DeleteComment($input: DeleteCommentInput!) {
  deleteComment(input: $input) {
    ... on Comment {
      id
      createdAt
      updatedAt
      description
      identifier
      index
      isHidden
      name
      numberOfClicks
      numberOfVotes
      numberOfViews
      userID
      user {
        ... on User {
          id
          username
          photoBase64
        }
      }
      answerID
      answer {
        ... on Answer {
          id
          description
          name
        }
      }
      files {
        items {
          ... on CommentFile {
            id
            createdAt
            updatedAt
            isHidden
            key
            name
            url
            userID
            commentID
            _deleted
            _lastChangedAt
            _version
          }
        }
      }
      votes {
        items {
          ... on CommentVote {
            id
            createdAt
            updatedAt
            isHidden
            userID
            commentID
            _deleted
            _lastChangedAt
            _version
          }
        }
      }
      _deleted
      _lastChangedAt
      _version
    }
  }
}
