query ListAllAnswerFiles {
  listAnswerFiles {
    items {
      ... on AnswerFile {
        id
        createdAt
        updatedAt
        isHidden
        key
        name
        url
        userID
        user {
          ... on User {
            id
            username
            photoBase64
          }
        }
        answerID
        answer {
          ... on Answer {
            id
            description
            name
          }
        }
        _deleted
        _lastChangedAt
        _version
      }
    }
  }
}
