query GetCommentFile($commentFileID: ID!) {
  getCommentFile(id: $commentFileID) {
    ... on CommentFile {
      id
      createdAt
      updatedAt
      isHidden
      key
      name
      url
      userID
      user {
        ... on User {
          id
          username
          photoBase64
        }
      }
      commentID
      comment {
        ... on Comment {
          id
          description
          name
        }
      }
      _deleted
      _lastChangedAt
      _version
    }
  }
}
