query SearchGroups(
  $isHidden: Boolean = false
  $organisationID: ID!
  $userID: ID
  $name: String
  $sortDirection: ModelSortDirection = DESC
) {
  latestGroups(
    organisationID: $organisationID
    filter: {isHidden: {eq: $isHidden}, and: {name: {contains: $name}}}
    sortDirection: $sortDirection
  ) {
    items {
      ... on Group {
        id
        createdAt
        updatedAt
        description
        icon
        identifier
        index
        isApproved
        isHidden
        name
        numberOfClicks
        numberOfQuestions
        numberOfUsers
        numberOfViews
        numberOfVotes
        organisationID
        organisation {
          ... on Organisation {
            id
            code
            name
          }
        }
        suggesterID
        suggester {
          ... on User {
            id
            username
          }
        }
        groupGroupTypeId
        groupType {
          ... on GroupType {
            id
            description
            icon
            identifier
            name
            organisationID
          }
        }
        users {
          items {
            id
            userID
            user {
              ... on User {
                id
                username
                userUserTypeId
                userType {
                  ... on UserType {
                    id
                    description
                    identifier
                    name
                  }
                }
              }
            }
            groupID
            group {
              ... on Group {
                id
                name
              }
            }
          }
        }
        questions {
          items {
            ... on Question {
              ... on Question {
                id
                createdAt
                updatedAt
                description
                identifier
                index
                isHidden
                name
                numberOfAnswers
                numberOfClicks
                numberOfSaves
                numberOfVotes
                numberOfViews
                userID
                groupID
                files {
                  items {
                    ... on QuestionFile {
                      id
                      createdAt
                      updatedAt
                      isHidden
                      name
                      url
                      userID
                      questionID
                      _deleted
                      _lastChangedAt
                      _version
                    }
                  }
                }
                saves(filter: {userID: {eq: $userID}, isHidden: {eq: false}}) {
                  items {
                    ... on QuestionSave {
                      id
                      createdAt
                      updatedAt
                      isHidden
                      userID
                      user {
                        ... on User {
                          id
                          username
                        }
                      }
                      questionID
                      question {
                        ... on Question {
                          id
                          description
                          name
                        }
                      }
                      _deleted
                      _lastChangedAt
                      _version
                    }
                  }
                }
                votes(filter: {userID: {eq: $userID}, isHidden: {eq: false}}) {
                  items {
                    ... on QuestionVote {
                      id
                      createdAt
                      updatedAt
                      isHidden
                      userID
                      user {
                        ... on User {
                          id
                        }
                      }
                      questionID
                      question {
                        ... on Question {
                          id
                        }
                      }
                      _deleted
                      _lastChangedAt
                      _version
                    }
                  }
                }
                _deleted
                _lastChangedAt
                _version
              }
            }
          }
        }
        tags {
          items {
            ... on GroupTagGroup {
              id
              groupTagID
              groupTag {
                ... on GroupTag {
                  id
                  description
                  identifier
                  name
                  organisationID
                }
              }
              groupID
              group {
                ... on Group {
                  id
                }
              }
            }
          }
        }
        votes(filter: {userID: {eq: $userID}, isHidden: {eq: false}}) {
          items {
            ... on GroupVote {
              id
              createdAt
              updatedAt
              isHidden
              userID
              user {
                ... on User {
                  id
                }
              }
              groupID
              group {
                ... on Group {
                  id
                }
              }
              _deleted
              _lastChangedAt
              _version
            }
          }
        }
        _deleted
        _lastChangedAt
        _version
      }
    }
  }
}
