query ListAllGroupVotesByGroupAndUser($groupID: ID, $userID: ID) {
  listGroupVotes(filter: {groupID: {eq: $groupID}, userID: {eq: $userID}}) {
    items {
      ... on GroupVote {
        id
        createdAt
        updatedAt
        isHidden
        userID
        user {
          ... on User {
            id
            username
            photoBase64
          }
        }
        groupID
        group {
          ... on Group {
            id
            description
            name
          }
        }
        _deleted
        _lastChangedAt
        _version
      }
    }
  }
}
